server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keyboard_planet #?serverTimezone=UTC
    username: root
  main:
    banner-mode: off

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto

keyboard-planet:
  path: D:\
